[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 20
y = 20

[font]
size = 16.0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[colors.normal]
black = '#000000'
blue = '#6699cc'
cyan = '#5fb4b4'
green = '#99c794'
magenta = '#c695c6'
red = '#ec5f66'
white = '#f7f7f7'
yellow = '#f9ae58'

[colors.bright]
black = '#808080'
blue = '#85add6'
cyan = '#82c4c4'
green = '#acd1a8'
magenta = '#d8b6d8'
red = '#f97b58'
white = '#ffffff'
yellow = '#fac761'

[colors.primary]
background = '#343d46'
foreground = '#d8dee9'

[colors.cursor]
cursor = '#fcbb6a'
text = '#ffffff'

[colors.selection]
background = '#4e5a65'
text = '#d8dee9'
