" basic settings
syntax enable
set nocompatible
set showmatch
set hlsearch
set incsearch
set noshowmode
set number
set hidden
set backspace=indent,eol,start
set ls=2
set foldmethod=indent
set foldlevel=99
set clipboard=unnamedplus
set wildmode=longest,list
set mouse=a

" default text formatting
set tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=80
set expandtab
set autoindent
set formatoptions-=t
set fileformat=unix
set encoding=utf-8

" text format overrides for 2-space tab stop file formats
au BufNewFile,BufRead *.css,*.ex,*.exs,*.html,*.js,*.json,*.jsx,*.lua,*.rb,*.ts,*.tsx
\     set tabstop=2 |
\     set softtabstop=2 |
\     set shiftwidth=2

" special syntax highlighing
autocmd FileType json syntax match Comment +\/\/.\+$+

" fundamental remaps
imap jk <Esc>
map <Space> <leader>

" recognize the alt key in terminals
if !has("nvim") && !has("gui_running")
  let c='a'
  while c <= 'z'
    exec "set <A-".c.">=\e".c
    exec "imap \e".c." <A-".c.">"
    let c = nr2char(1+char2nr(c))
  endw

  set timeout ttimeoutlen=50
endif

" moves
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
nnoremap <C-l> >>_
nnoremap <C-h> <<_
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv
vnoremap <C-l> >gv
vnoremap <C-h> <gv

" splits
set splitbelow
set splitright
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
map <A-j> :resize -4<CR>
map <A-k> :resize +4<CR>
map <A-l> :vertical:resize -4<CR>
map <A-h> :vertical:resize +4<CR>
nnoremap <leader>wd <C-W>c
nnoremap <leader>ws <C-W>s
nnoremap <leader>wv <C-W>v
nnoremap <leader>wh <C-W>h
nnoremap <leader>wl <C-W>l
nnoremap <leader>wj <C-W>j
nnoremap <leader>wk <C-W>k

" files
nmap <leader>fs :w<CR>
nmap <leader>wq :wq<CR>

" tabs
nmap <leader>tn :tabnew<CR>
nmap <leader>td :tabclose<CR>
nmap <leader>tp :tabp<CR>
nmap <leader>tn :tabn<CR>

" buffers
nmap <leader>bp :bp<CR>
nmap <leader>bn :bn<CR>
nmap <leader>bd :bd<CR>
nmap <leader>bq :q<CR>
nmap <leader>bQ :q!<CR>

" ui
set fillchars+=vert:\│
set signcolumn=yes
highlight clear SignColumn

if exists('+termguicolors')
    let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
    set background=dark
endif

" allow project-specific overrides
set exrc
set secure

if !has("nvim") && !empty(globpath(&rtp, 'autoload/plug.vim'))
    call plug#begin()

    " editor features
    Plug 'airblade/vim-gitgutter'
    Plug 'jeffkreeftmeijer/vim-numbertoggle'
    Plug 'jiangmiao/auto-pairs'
    Plug 'sheerun/vim-polyglot'
    Plug 'tpope/vim-abolish'
    Plug 'tpope/vim-commentary'
    Plug 'tpope/vim-endwise'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-sensible'
    Plug 'tpope/vim-surround'

    " status line
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'

    " color schemes
    Plug 'chadnorvell/mariana.vim'
    Plug 'chadnorvell/oceanic-next'

    call plug#end()

    " colors
    colorscheme mariana
    let g:airline_theme='oceanicnext'
endif
